@baseURL = http://localhost:5000
@urlPath = api/v1/skills
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoibmd1eWVuZHUxMUBnbWFpbC5jb20iLCJuYW1lIjoiTmd1eWVuIEh1eSBEdSIsInJvbGVzIjpbInJlY3J1aXRlciJdLCJpYXQiOjE3NjM2OTc5NTIsImV4cCI6MTc2Mzc4NDM1MiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9._BZPQyGvg_zaa55vc42lE2zVs5Hx3kroxyDQ-T6M-2E

### CREATE SKILL
POST {{baseURL}}/{{urlPath}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name":"TS"
}

### GET ALL SKILLS
GET {{baseURL}}/{{urlPath}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET SKILL
GET {{baseURL}}/{{urlPath}}/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### UPDATE SKILL BY ID
PATCH {{baseURL}}/{{urlPath}}/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "name": "French"
}

### DELETE SKILL BY ID
DELETE {{baseURL}}/{{urlPath}}/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}
