@baseURL = http://localhost:5000
@urlPath = api/v1/orders
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibmd1eWVuZHVAZ21haWwuY29tIiwibmFtZSI6Ik5ndXllbiBIdXkgRHUiLCJyb2xlcyI6W10sImlhdCI6MTc2MzYyMTc5NywiZXhwIjoxNzYzNzA4MTk3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.3ANQHHm9KOu_K6l_Vd5eIiSPYKeuk5GjKt4czq8gm1g

### CREATE ORDER
POST {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}


### DELETE ORDER
DELETE  {{baseURL}}/{{urlPath}}/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}


