@baseURL = http://localhost:5000
@urlPath = api/v1/packages
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibmd1eWVuZHVAZ21haWwuY29tIiwibmFtZSI6Ik5ndXllbiBIdXkgRHUiLCJyb2xlcyI6W10sImlhdCI6MTc2MzYyMTEyNSwiZXhwIjoxNzYzNzA3NTI1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.D_ocqUM_W8JtOiWdmixfCpEXvPFw9EROrSvFnHvL1vQ

### CREATE PACKAGE
POST {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "label": "Enterprise VIP",
  "price": 10000000,
  "jobPostLimit": 100,
  "duration": 30,
  "isActive": false
}

### GET ALL PACKAGES
GET {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET PACKAGES
GET {{baseURL}}/{{urlPath}}/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET PACKAGES ACTIVED
GET {{baseURL}}/{{urlPath}}/active
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### UPDATE PACKAGES
PATCH  {{baseURL}}/{{urlPath}}/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "isActive": true
}

### DELTE PACKAGE
DELETE  {{baseURL}}/{{urlPath}}/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}






