@baseURL = http://localhost:5000
@urlPath = api/v1/company-industries
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6Im5ndXllbmR1QGdtYWlsLmNvbSIsIm5hbWUiOiJOZ3V5ZW4gSHV5IER1Iiwicm9sZXMiOlsiQ0FORElEQVRFIl0sImlhdCI6MTc2MzQ3OTcwOSwiZXhwIjoxNzYzNTY2MTA5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.k8PKcDb5MxCanfZAKCCAxAyGnAOFxOl46__w-K_XMHo

### CREATE CANDIDATE LANGUAGE
POST {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
    "industryIds": [2]
}

### GET MY LANGUAGE
GET {{baseURL}}/{{urlPath}}/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}
