@baseURL = http://localhost:3000
@urlPath = api/v1/company-images/company
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEzLCJlbWFpbCI6Im5ndXllbmR1QGdtYWlsLmNvbSIsIm5hbWUiOiJOZ3V5ZW4gSHV5IER1Iiwicm9sZXMiOlsiQ0FORElEQVRFIl0sImlhdCI6MTc2MzQ1NzM2NywiZXhwIjoxNzYzNTQzNzY3LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.1tuhDmH3jdS8UjScGGAUpSEdB80RISuexPiE2u5Sjy0

### CREATE COMPANY IMAGES
POST {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
}

### GET COMPANY IMAGES BY COMPANY ID
GET {{baseURL}}/{{urlPath}}/8
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### DELTE IMAGE BY ID
DELETE  {{baseURL}}/{{urlPath}}/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

