@baseURL = http://localhost:5000
@urlPath = api/v1/roles
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibmd1eWVuZHVAZ21haWwuY29tIiwibmFtZSI6Ik5ndXllbiBIdXkgRHUiLCJyb2xlcyI6W10sImlhdCI6MTc2MzY5NTcwOSwiZXhwIjoxNzYzNzgyMTA5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.Hc5gKRxViL7EfUyShRf2WcCH3Vl12Hvqx4gh_XjEfy8

### CREATE ROLE
POST {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "admin",
  "description": "Quản trị viên",
  "isSystem": true
}

### GET ALL ROLES
GET {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET ROLE BY ID
GET {{baseURL}}/{{urlPath}}/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### UPDATE ROLE
Patch {{baseURL}}/{{urlPath}}/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "ADMIN",
  "description": "Quản trị viên hệ thống"
}

### DELETE ROLE
DELETE {{baseURL}}/{{urlPath}}/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}


