@baseURL = http://localhost:3000
@urlPath = api/v1/roles
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoibmd1eWVuaHV5ZHU0MzJAZ21haWwuY29tIiwibmFtZSI6Ik5ndXllbiBIdXkgRHUiLCJpYXQiOjE3NjI1ODI5MTksImV4cCI6MTc2MjU4MzgxOSwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.tMaKaM5oN02-D6AYqzFul_n-JecHuQOHQZL4OMrvnCo

### CREATE ROLE
POST {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "CANDIDATE",
  "description": "Người tuyển dụng",
  "isSystem": true,
  "permissions": [
    {
      "resource": "roles",
      "actions": ["read", "update", "delete", "create"]
    },
    {
      "resource": "users",
      "actions": ["read", "update"]
    }
  ]
}

### GET ALL ROLES
GET {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### GET ROLE BY ID
GET {{baseURL}}/{{urlPath}}/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

### UPDATE ROLE
Patch {{baseURL}}/{{urlPath}}/3
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "ADMIN",
  "description": "Quản trị viên hệ thống",
  "permissions": [
    {
      "resource": "roles",
      "actions": ["read", "update", "delete", "create", "delete" ]
    },
    {
      "resource": "users",
      "actions": ["read", "update", "create"]
    }
  ]
}

### DELETE ROLE
DELETE {{baseURL}}/{{urlPath}}/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}


