@baseURL = http://localhost:3000
@urlPath = api/v1/user-roles
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoibmd1eWVuaHV5ZHU0MzJAZ21haWwuY29tIiwibmFtZSI6Ik5ndXllbiBIdXkgRHUiLCJpYXQiOjE3NjI1ODQ2ODQsImV4cCI6MTc2MjU4NTU4NCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.rA08zi-NTm-msztHy0zUtKBiy15v0dCac34LKNgTNM0
### Assign Role To User
POST {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": 6,
  "roleIds": [4,5,6]
}

### Get all roles by User ID
GET {{baseURL}}/{{urlPath}}/6
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}


### Delete role from user
DELETE  {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": 6,
  "roleId": 1
}



