@baseURL = http://localhost:5000
@urlPath = api/v1/user-roles
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoibmd1eWVuZHVAZ21haWwuY29tIiwibmFtZSI6Ik5ndXllbiBIdXkgRHUiLCJyb2xlcyI6W10sImlhdCI6MTc2MzY5NTcwOSwiZXhwIjoxNzYzNzgyMTA5LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.Hc5gKRxViL7EfUyShRf2WcCH3Vl12Hvqx4gh_XjEfy8

### Assign Role To User
POST {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": 4,
  "roleIds": [3]
}

### Get all roles by User ID
GET {{baseURL}}/{{urlPath}}/6
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}


### Delete role from user
DELETE  {{baseURL}}/{{urlPath}}/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "userId": 6,
  "roleId": 1
}



